<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>annotations</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>false</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgebraicTermRewriter\AlgebraicTermRewriter.csproj" />
  </ItemGroup>

</Project>